apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-hellow-10
  namespace: ace
spec:
  configurations: []
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace/ace-hellow:1.0
        imagePullPolicy: Always
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  tracing:
    enabled: true
    namespace: tracing
  useCommonServices: true
  version: 12.0.1.0-r3
