apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acecicd-pipeline
spec:
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  tasks:
  - name: build-image
    taskRef:
      name: task-dockerf-build-push
    resources:
      inputs:
      - name: source
        resource: git-repo
      - name: image
        resource: image
    params:
    - name: TLSVERIFY
      value: "false"
  - name: deploy-image
    taskRef:
      name: task-deploy-aceimg
    runAfter:
      - build-image
    resources:
      inputs:
      - name: image
        resource: image
    params:
    - name: namespace
      value: ace
    - name: image_name
      value: $(tasks.build-image.results.image_name)
    - name: image_tag
      value: $(tasks.build-image.results.image_tag)
