apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acecicd-pack-test-build-acesrv
spec:
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  params:
  - name: namespace
    default: ace
    description: namespace used to publish the integration server
  - name: IMGTAG
    default: "1.0"
    description: tag for the ace image that will be build
  tasks:
  - name: ptb-aceserver
    taskRef:
      name: pack-test-build-aceserver
    resources:
      inputs:
      - name: source
        resource: git-repo
      - name: image
        resource: image
    params:
    - name: namespace
      value: $(params.namespace)
    - name: IMGTAG 
      value: $(params.IMGTAG)