apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-build-aceminimal
spec:
  params:
    - name: aceDownloadUrl
      type: string
      default: http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/integration/12.0.1.0-ACE-LINUX64-DEVELOPER.tar.gz
    - name: namespace
      default: ace
      description: namespace used to build the image url
  results:
    - name: image_tag
      description: tag from git acecfg for image
    - name: image_name
      description: name from git acecfg for image
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        cd /work
        git clone "https://github.com/tdolby-at-uk-ibm-com/ace-docker"
        ls -l /work/ace-docker/experimental/ace-minimal
      volumeMounts:
        - mountPath: /work
          name: work
    - name: ace-minimal-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/work/ace-docker/experimental/ace-minimal/Dockerfile.alpine
        - --destination=$(resources.inputs.image.url)/$(params.namespace)/ace-minimal:12.0.1.0-alpine
        - --context=/work/ace-docker/experimental/ace-minimal
        - --build-arg=DOWNLOAD_URL=$(params.aceDownloadUrl)
        - --skip-tls-verify
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}