apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-aceimg
  labels:
    app.kubernetes.io/name: ace-cicd
    app.kubernetes.io/component: deploy
spec:
  params:
    - default: ace
      description: release namespace
      name: namespace
      type: string
    - name: integrationServerName
      description: name of the integration server
    - name: image_tag
      description: image tag name
    - name: image_name
      description: image name
    - name: license
      description: license number
      default: L-APEH-C49KZH
    - name: tracing_ns
      default: tracing
      description: namespace where OD is installed
    - name: tracing_enabled
      default: "true"
      description: enable tracing
    - name: ace_version
      default: 12.0.2.0-r1
      description: fully qualified ace version
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: create-integrationserver
      resources: {}
      script: |
        #!/bin/bash
        set -e  # Exit on error

        # Sanitize integration server name (remove dots)
        ISNAME=$(echo "$(params.integrationServerName)" | tr -d '.')

        echo "==> Deploying IntegrationServer: $ISNAME"
        echo "==> Namespace: $(params.namespace)"
        echo "==> Image: $(resources.inputs.image.url)/$(params.namespace)/$(params.image_name):$(params.image_tag)"

        # Generate IntegrationServer custom resource
        cat << EOF > integrationserver.yaml
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $ISNAME
          namespace: $(params.namespace)
          labels:
            app: ace
            app.kubernetes.io/name: $ISNAME
            app.kubernetes.io/managed-by: tekton
        spec:
          pod:
            containers:
              runtime:
                image: $(resources.inputs.image.url)/$(params.namespace)/$(params.image_name):$(params.image_tag)
                imagePullPolicy: Always
          configurations: []
          designerFlowsOperationMode: disabled
          createDashboardUsers: true
          adminServerSecure: true
          license:
            accept: true
            license: $(params.license)
            use: CloudPakForIntegrationNonProduction
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          tracing:
            enabled: $(params.tracing_enabled)
            namespace: $(params.tracing_ns)
          version: $(params.ace_version)
        EOF

        echo "==> Generated IntegrationServer manifest:"
        cat integrationserver.yaml

        echo "==> Applying IntegrationServer CR"
        oc apply -f integrationserver.yaml

        echo "==> Waiting for IntegrationServer to be ready (max 5 minutes)"
        oc wait --for=condition=Ready integrationserver/$ISNAME \
          -n $(params.namespace) --timeout=300s || true

        echo "==> Deployment status:"
        oc get integrationserver/$ISNAME -n $(params.namespace)
