apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acecicd-process-git
spec:
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  params:
  - name: namespace
    default: ace
    description: namespace used to publish the integration server
  tasks:
  - name: 1-get-git-config
    taskRef:
      name: get-config
    resources:
      inputs:
      - name: source
        resource: git-repo
  - name: 2-pack-test-build-aceimg
    taskRef:
      name: pack-test-build-aceserver
    runAfter:
      - 1-get-git-config
    resources:
      inputs:
      - name: source
        resource: git-repo
      - name: image
        resource: image
    params:
    - name: namespace
      value: $(params.namespace)
    - name: IMG_NAME
      value: $(tasks.1-get-git-config.results.image_name)
    - name: IMG_TAG
      value: $(tasks.1-get-git-config.results.image_tag)
    - name: ACE_APP_NAME
      value: $(tasks.1-get-git-config.results.aceapp_name)
  - name: 3-deploy-image
    taskRef:
      name: deploy-aceimg
    runAfter:
      - 2-pack-test-build-aceimg
    resources:
      inputs:
      - name: image
        resource: image
    params:
    - name: namespace
      value: $(params.namespace)
    - name: integrationServerName
      value: $(tasks.1-get-git-config.results.image_name)-$(tasks.1-get-git-config.results.image_tag)
    - name: image_name
      value: $(tasks.1-get-git-config.results.image_name)
    - name: image_tag
      value: $(tasks.1-get-git-config.results.image_tag)
    - name: ace_version
      value: 12.0.2.0-r1
    - name: license
      value: L-APEH-C49KZH
