apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-unittest-ace
spec:
  params:
    - default: ibmcom/ace-server:latest
      description: aceserver image
      name: ACE_IMAGE
      type: string
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - name: unit-test
      image: $(params.ACE_IMAGE)
      script: |
        ls -la
        ls bars
        . ./imgcfg
        . /opt/ibm/ace-11/server/bin/mqsiprofile
        mkdir unittestserver
        mqsicreateworkdir unittestserver
        cd source/PingServiceUnitTest


        mqsipackagebar -a ../bars/Integration.bar -k PingService
        if [[ -e "PingService/PingService.properties" ]]
        then
          mqsiapplybaroverride -b ../bars/Integration.bar -k PingService -p PingService/PingService.properties -o ../bars/IntegrationOver.bar
          rm ../bars/Integration.bar
          mv ../bars/IntegrationOver.bar ../bars/Integration.bar
        fi
        cat PingService/ping_Get_data.esql
        ls ../bars
      securityContext:
        privileged: true
      resources: {}
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
         
