apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-aceimg
spec:
  params:
    - default: ace
      description: release namespace
      name: namespace
      type: string
    - name: integrationServerName
      description: name of the integration server
    - name: image_tag
      description: image tag name
    - name: image_name
      description: image name
    - name: license
      description: license number
      default: L-KSBM-BZWEAT
    - name: tracing_ns
      default: tracing
      description: namespace where OD is installed
    - name: tracing_enabled
      default: "false"
      description: enable tracing
    - name: ace_version
      default: 11.0.0.12-r1
      description: fully qualified ace version
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: oc
      resources: {}
      script: |
        ISNAME=$(echo "$(params.integrationServerName)" | tr -d .)
        cat << EOF > integrationserver.yaml
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $ISNAME
          namespace: $(params.namespace)
        spec:
          pod:
           containers:
             runtime:
               image: $(resources.inputs.image.url)/$(params.namespace)/$(params.image_name):$(params.image_tag)
          configurations: []
          designerFlowsOperationMode: disabled
          license:
            accept: true
            license: $(params.license)
            use: CloudPakForIntegrationNonProduction
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          tracing:
            enabled: $(params.tracing_enabled)
            namespace: $(params.tracing_ns)
          version: $(params.ace_version)
        EOF
        cat integrationserver.yaml
        oc apply -f integrationserver.yaml
