apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-prepare-aceserver
spec:
  params:
    - default: ibmcom/ace-server:latest
      description: aceserver image
      name: ACE_IMAGE
      type: string
    - default: registry.redhat.io/rhel8/buildah
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: 'false'
      description: Verify the TLS on the registry endpoint
      name: TLSVERIFY
      type: string
    - name: namespace
      default: ace
      description: namespace used to build the image url
    - name: "IMGNAME"
      description: "image name"
      default: "ace-cicd"
      type: string
    - name: "IMGTAG"
      description: "image tag"
      default: "1.0"
      type: string
  results:
    - name: image_tag
      description: tag from git acecfg for image
    - name: image_name
      description: name from git acecfg for image
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: prepare-bar
      image: $(params.ACE_IMAGE)
      script: |
        ls -la
        rm bars/*
        ls bars
        . ./imgcfg
        . /opt/ibm/ace-11/server/bin/mqsiprofile
        cd source
        mqsipackagebar -a ../bars/Integration.bar -k PingService
        if [[ -e "PingService/PingService.properties" ]]
        then
          mqsiapplybaroverride -b ../bars/Integration.bar -k PingService -p PingService/PingService.properties -o ../bars/IntegrationOver.bar
          rm ../bars/Integration.bar
          mv ../bars/IntegrationOver.bar ../bars/Integration.bar
        fi
        cat PingService/ping_Get_data.esql
        ls ../bars
      securityContext:
        privileged: true
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
    - name: ace-minimal-build-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --destination=$(resources.inputs.image.url)/$(params.namespace)/$(params.IMGNAME):$(params.IMGTAG)
        - --context=.
        - --build-arg=BASE_IMAGE=$(resources.inputs.image.url)/$(params.namespace)/$(params.IMGNAME):$(params.IMGTAG)
        - --skip-tls-verify
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
  volumes:
    - emptyDir: {}
      name: varlibcontainers