apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-dockerf-build-push
spec:
  params:
    - default: registry.redhat.io/rhel8/buildah
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: 'false'
      description: Verify the TLS on the registry endpoint
      name: TLSVERIFY
      type: string
    - name: namespace
      default: ace
      description: namespace used to build the image url
  results:
    - name: image_tag
      description: tag from git acecfg for image
    - name: image_name
      description: name from git acecfg for image
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: build
      image: $(params.BUILDER_IMAGE)
      script: |
        ls ./bars
        . ./imgcfg
        buildah bud --storage-driver=vfs --format=oci \
          --tls-verify=$(params.TLSVERIFY) --layers \
          -f $(params.DOCKERFILE) -t $(resources.inputs.image.url)/$(params.namespace)/$imgname:$imgtag .
      securityContext:
        privileged: true
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
    - name: push
      script: |
        . ./imgcfg
        buildah push --storage-driver=vfs --tls-verify=$(params.TLSVERIFY) \
          $(resources.inputs.image.url)/$(params.namespace)/$imgname:$imgtag \
          'docker://$(resources.inputs.image.url)/$(params.namespace)/'$imgname:$imgtag
        echo -n $imgtag > /tekton/results/image_tag
        echo -n $imgname > /tekton/results/image_name
      image: $(params.BUILDER_IMAGE)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
  volumes:
    - emptyDir: {}
      name: varlibcontainers