apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acecicd-build-acemin-img
spec:
  resources:
  - name: image
    type: image
  params:
  - name: namespace
    default: ace
    description: namespace used to publish the integration server
  tasks:
  - name: build-aceimg
    taskRef:
      name: build-aceminimal
    resources:
      inputs:
      - name: image
        resource: image
    params:
    - name: namespace
      value: $(params.namespace)