apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: acecicd-res-git
spec:
  type: git
  params:
  - name: revision
    value: main
  - name: url
    value: https://github.com/prichelle/pipeline-ace.git
