apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pack-test-build-aceserver
  labels:
    app.kubernetes.io/name: ace-cicd
    app.kubernetes.io/component: build
spec:
  params:
    - default: image-registry.openshift-image-registry.svc:5000/ace/ace-minimal:12.0.2
      description: aceserver image
      name: ACE_IMAGE
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/ace/ace-mvn:1.0
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: 'false'
      description: Verify the TLS on the registry endpoint
      name: TLSVERIFY
      type: string
    - name: namespace
      default: ace
      description: namespace used to build the image url
    - name: ACE_APP_NAME
      description: name of the ace application to build in the git repo.
      default: HelloWorld
      type: string
    - name: IMG_NAME
      description: name of the image that will be pushed in the registry
      default: ace-helloword
      type: string
    - name: IMG_TAG
      description: tag value to used to tag the image that will be pushed.
      default: "1.0"
      type: string
  results:
    - name: image_tag
      description: tag from git acecfg for image
    - name: image_name
      description: name from git acecfg for image
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: prepare-bar
      image: $(params.ACE_IMAGE)
      script: |
        #!/bin/bash
        set -e  # Exit on error

        echo "==> Preparing BAR file (v1.0)"
        export LICENSE="accept"

        # Source ACE environment
        . /opt/ibm/ace-12/server/bin/mqsiprofile

        # Clean existing BAR files
        rm -f bars/*.bar

        aceappname="$(params.ACE_APP_NAME)"
        echo "==> Building Integration BAR file for application: $aceappname"

        cd source
        mqsipackagebar -a ../bars/Integration.bar -k "$aceappname"

        # Apply property overrides if properties file exists
        if [[ -f "$aceappname/$aceappname.properties" ]]; then
          echo "==> Applying properties to BAR file"
          mqsiapplybaroverride -b ../bars/Integration.bar -k "$aceappname" \
            -p "$aceappname/$aceappname.properties" -o ../bars/IntegrationOver.bar
          mv ../bars/IntegrationOver.bar ../bars/Integration.bar
          echo "==> Properties applied:"
          cat "$aceappname/$aceappname.properties"
        else
          echo "==> No properties file found, skipping override"
        fi

        echo "==> BAR files created:"
        ls -lh ../bars/
        
      securityContext:
        privileged: true
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
    - name: run-unittest
      image: $(params.BUILDER_IMAGE)
      script: |
        #!/bin/bash
        set -e  # Exit on error

        echo "==> Running unit tests"

        # Source ACE environment
        . /opt/ibm/ace-12/server/bin/mqsiprofile
        export JAVA_HOME=/opt/ibm/ace-12/common/jdk
        export PATH=/opt/ibm/ace-12/common/jdk/bin:$PATH

        echo "==> MQSI Base Path: $MQSI_BASE_FILEPATH"

        # Load configuration
        . ./imgcfg

        # Build unit test project with Maven
        echo "==> Compiling test project: $unittestprj"
        cd "source/$unittestprj"

        # Use mvn from PATH (works with any Maven version)
        mvn --no-transfer-progress -Dinstall.work.directory=../maven-output clean install

        echo "==> JAR file generated:"
        ls -lh *.jar

        # Prepare test server
        echo "==> Preparing test server: ACE_UnitTest_Srv"
        cd ../..
        mqsicreateworkdir ACE_UnitTest_Srv
        mkdir -p ACE_UnitTest_Srv/run/UnitTestProject/resources

        # Copy test artifacts
        echo "==> Copying unit test artifacts"
        cp "source/$unittestprj/$unittestprj-maven.jar" ACE_UnitTest_Srv/run/UnitTestProject/
        cp "source/$unittestprj/testproject.descriptor" ACE_UnitTest_Srv/run/UnitTestProject/

        if [[ -d "source/$unittestprj/src/main/resources" ]]; then
          cp source/$unittestprj/src/main/resources/* ACE_UnitTest_Srv/run/UnitTestProject/resources/ || true
        fi

        echo "==> Copying Integration BAR file"
        cp bars/Integration.bar ACE_UnitTest_Srv/run/

        echo "==> Executing unit tests"
        IntegrationServer \
          --work-dir ACE_UnitTest_Srv \
          --no-nodejs \
          --test-project UnitTestProject \
          --start-msgflows false \
          --http-port-number -1 \
          --admin-rest-api -1

        echo "==> Unit tests completed successfully"
      securityContext:
        privileged: true
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
    - name: build-push-acesrv
      # Updated to newer Kaniko version for better performance and security
      image: gcr.io/kaniko-project/executor:v1.23.0
      # DOCKER_CONFIG is required to allow kaniko to detect docker credentials
      # SSL_CERT_DIR is set to avoid certificate conflicts with Tekton volume mounts
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
        - name: "SSL_CERT_DIR"
          value: "/tmp/other-ssl-dir"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --destination=$(resources.inputs.image.url)/$(params.namespace)/$(params.IMG_NAME):$(params.IMG_TAG)
        - --context=.
        - --build-arg=BASE_IMAGE=$(resources.inputs.image.url)/$(params.namespace)/$(params.IMG_NAME):$(params.IMG_TAG)
        - --skip-tls-verify
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
  volumes:
    - emptyDir: {}
      name: varlibcontainers