apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acecicd-pipeline-acemvn
spec:
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  params:
  - name: namespace
    default: ace
    description: namespace used to publish the integration server
  tasks:
  - name: prepare-acemvn
    taskRef:
      name: task-prepare-acemvn
    resources:
      inputs:
      - name: source
        resource: git-repo
      - name: image
        resource: image
    params:
    - name: namespace
      value: $(params.namespace)