apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: acecicd-process-git-trigger
  labels:
    app.kubernetes.io/name: ace-cicd
    app.kubernetes.io/component: trigger
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: acecicd-pipeline-run-
      namespace: ace
      labels:
        tekton.dev/pipeline: acecicd-pipeline
        app.kubernetes.io/name: ace-cicd
    spec:
      pipelineRef:
        name: acecicd-process-git
      resources:
        - name: git-repo
          resourceRef:
            name: acecicd-res-git
        - name: image
          resourceRef:
            name: acecicd-res-image
      serviceAccountName: pipeline
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: acecicd-listener
  labels:
    app.kubernetes.io/name: ace-cicd
    app.kubernetes.io/component: eventlistener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: acecicd-process-git-trigger
    triggerRef: acecicd-process-git-trigger
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: acecicd-listener
  name: acecicd-webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-acecicd-listener
