apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-acemvn-img
spec:
  params:
    - default: image-registry.openshift-image-registry.svc:5000/ace/ace-minimal:12.0.1.0-alpine
      description: aceserver image
      name: ACE_IMAGE
      type: string
    - default: DockerFileMvn
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - name: namespace
      default: ace
      description: namespace used to build the image url
    - name: "IMGNAME"
      description: "image name"
      default: "ace-mvn"
      type: string
    - name: "IMGTAG"
      description: "image tag"
      default: "1.0"
      type: string
  results:
    - name: image_tag
      description: tag from git acecfg for image
    - name: image_name
      description: name from git acecfg for image
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: ace-mvn-build-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --destination=$(resources.inputs.image.url)/$(params.namespace)/$(params.IMGNAME):$(params.IMGTAG)
        - --context=.
        - --build-arg=BASE_IMAGE=$(params.ACE_IMAGE)
        - --skip-tls-verify
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
  volumes:
    - emptyDir: {}
      name: varlibcontainers